"""Verifier agent: generate + run an execution-based verification script.

The verifier proves the task was carried out correctly. It assembles ONE python
script (``verify.py``) combining three evaluator families, then executes it:

  (1) Format Evaluators  — strict structure checks on each step's trace entry.
      Deterministic.
  (2) Static Evaluators  — value checks on the arguments actually sent.
      Deterministic.
  (3) Dynamic Evaluators — real-time / metamorphic checks that re-query the
      database live through a fresh RESTRICTED (read-only) postgres-mcp
      session (e.g. "the table now exists and holds exactly 3 rows"). This
      section is generated by the LLM, grounded on the tool's Python
      implementation + unit test, then compile-checked and sandboxed so a bad
      snippet can't crash verification.

Between (1) and (3) sits a deterministic live layer, ``sql_write_evaluators``:
every executed CREATE/DROP is re-checked for existence/absence at the exact
object it named, and every INSERT contributes a row-count floor for its table
— no LLM judgment involved. Row CONTENT correctness stays in the dynamic layer
(grounded on the executed SQL, never re-typed from task prose).

This hybrid (deterministic core + LLM-only-for-dynamic) is the key reliability
optimization over fully LLM-generated verification scripts.
"""

from __future__ import annotations

import ast
import json
import re
import subprocess
import sys
import textwrap
from dataclasses import dataclass
from typing import Any

from .toolsource import load_for_verifier
from .config import LLMClient, Settings, extract_json
from .executor import ExecutionTrace
from .planner import Plan

_DYNAMIC_SYSTEM = """\
You write the BODY of one Python function that VERIFIES a PostgreSQL task was \
done correctly, by re-querying the database live (read-only).

You are given (as JSON): the task, available_tools, the plan steps with their \
post_action_properties, the executed steps with arguments_resolved and \
result_data, and the Python impl/test of the tools used.

Write ONLY Python statements (no `def` line, no imports, no markdown) forming \
the body of:  def dynamic_evaluators(pg):

USE ONLY THESE pre-defined helpers for live queries — do NOT call pg.call \
directly (raw tool signatures vary and are error-prone):
  - pg_rows(pg, sql) -> list[dict] | None       # run ONE read-only SELECT/SHOW; None on error; rows keyed by column alias
  - pg_scalar(pg, sql) -> value | None          # first column of first row, or None
  - pg_schemas(pg) -> list[str]                 # schema names, lowercase
  - pg_objects(pg, schema, object_type="table") -> list[dict]   # {schema,name,type} dicts from the server
  - pg_object_names(pg, schema, object_type="table") -> list[str]  # names, lowercase
  - pg_table_exists(pg, schema, table) -> bool
  - pg_columns(pg, schema, table) -> list[dict] # {column,data_type,is_nullable,default}
  - pg_constraints(pg, schema, table) -> list[dict]  # {name,type,columns}; type is UPPERCASE: 'PRIMARY KEY'|'UNIQUE'|'CHECK'|'FOREIGN KEY'; carries NO clause text
  - pg_check_clauses(pg, schema, table) -> list[dict]  # {name, clause}: each CHECK constraint's SQL clause text
  - pg_matviews(pg, schema) -> list[str]        # materialized-view names (they exist ONLY here)
  - pg_indexes(pg, schema, table) -> list[dict] # {name,definition}
  - pg_count(pg, qualified_table, where=None) -> int | None  # SELECT count(*), optional WHERE clause (no 'WHERE' keyword)
  - pg_column_domain(pg, schema, table, column) -> str|None  # the DOMAIN a column is typed with (data_type only shows the base type)
  - vals_equal(a, b) -> bool                    # tolerant scalar equality: '100'==100, '230.0'==230, case-insensitive strings
  - rows_equal(rows, expected, ordered=True) -> bool  # tolerant row comparison (dicts or tuples); False on None, never raises
  - poll(predicate, timeout=30, interval=5) -> (ok, value)   # predicate()->(ok,value); rarely needed — commits are immediately visible
Also in scope: check(category, name, passed, detail) — ALWAYS category="dynamic"; \
the TRACE and PLAN dicts; the `time` module. TRACE and PLAN are DICTS — to \
iterate steps use the list aliases `executed_steps` (= TRACE["steps"]) and \
`plan_steps` (= PLAN["steps"]); NEVER iterate TRACE or PLAN directly.

Rules:
  - If `pg is None`: check("dynamic","live_requery",True,"skipped, no database"); return.
  - Derive schema/table/column names and EXPECTED VALUES from \
executed_steps[*].arguments_resolved (the exact SQL that was sent) and from \
values the task itself quotes. NEVER re-type quoted content from the task \
prose when the executed SQL carries it — copy it from the SQL argument. \
NEVER re-derive a value by re-implementing a formula the SQL computed \
(generate_series arithmetic, modulo buckets, date math): re-query the value \
and assert simple properties, or compare two live queries to each other.
  - ALL value comparisons go through vals_equal / rows_equal — never bare == \
or != on values read from the database ('100' vs 100 and '230.0' vs 230 are \
the same value; bare == makes the check fail on formatting, not substance).
  - DDL EXISTENCE IS ALREADY VERIFIED: a deterministic evaluator re-checks \
every executed CREATE/DROP and every INSERT's row-count floor. Do NOT repeat \
bare existence checks; verify CONTENT and RELATIONS instead: row values match \
what was inserted/updated, aggregates are right, a view returns the expected \
rows, an index's definition covers the right columns.
  - Verify the OBSERVABLE OUTCOMES the task asked for, NOT implementation \
details. Do not assert on the wording of text reports (explain plans, health \
reports) beyond what the task explicitly requires. EXPLAIN wording varies \
with the chosen plan (filters may be folded away, values quoted like \
::"char", and VIEWS expand — pg_settings appears as 'Function Scan on \
pg_show_all_settings', never as 'pg_settings'): assert at most that the \
explain step succeeded and returned a non-empty plan. NEVER assert that a \
plan USES an index — PostgreSQL legitimately seq-scans small tables even \
when a perfect index exists; verify the index's EXISTENCE via pg_indexes \
instead.
  - PostgreSQL folds unquoted identifiers to lowercase — always compare \
schema/table/column names lowercased.
  - Column TYPE names are reported canonically, not as written: an ARRAY \
column's data_type is exactly "ARRAY" (never "integer[]"/"text[]"), \
`varchar(n)` reads as "character varying", `int`/`int4` as "integer", \
`timestamptz` as "timestamp with time zone", and a custom enum/domain as \
"USER-DEFINED". Assert with a case-insensitive check against the CANONICAL \
name, or skip the type check and verify the stored VALUES instead.
  - Some result fields are SYNTHESIZED by the tools and are NOT real catalog \
columns: `schema_type` (list_schemas) and the tables' `type` label come from \
CASE expressions inside the tool. Verify them through pg_schemas/pg_objects \
(which return the server's own rows) — never SELECT them from \
information_schema (the column does not exist there and the query fails).
  - To verify a PRIMARY KEY / UNIQUE / CHECK / FOREIGN KEY use \
pg_constraints(pg, schema, table) and match `type` UPPERCASE (e.g. \
any(c["type"] == "PRIMARY KEY" and "id" in c["columns"] for c in cons)). \
NEVER hunt for the words "primary key" in pg_indexes definitions — a PK's \
index is just `CREATE UNIQUE INDEX <table>_pkey ...`, so that text search \
always fails.
  - A CHECK constraint's allowed values live ONLY in its clause: use \
pg_check_clauses(pg, schema, table) and search the `clause` text — \
pg_constraints gives just names/types, and asserting values against a \
constraint NAME always fails. PostgreSQL NORMALIZES stored clauses (extra \
parentheses, ::text casts, ANY(ARRAY[...]) rewrites): test that the COLUMN \
name and each boundary/allowed VALUE appear as substrings — never match a \
whole clause verbatim.
  - pg_objects/pg_object_names return ONLY the object_type you ask for \
(default "table" — BASE TABLEs only). A VIEW never appears there: check \
views with pg_objects(pg, schema, "view"), sequences with "sequence". \
A MATERIALIZED VIEW appears in NONE of them (it is absent from \
information_schema entirely) — use pg_matviews(pg, schema) for its \
existence, and for its COLUMNS or contents run \
pg_rows(pg, "SELECT * FROM <schema>.<mv> ...") and read the row keys \
(pg_columns/get_object_details cannot see a matview and return []).
  - NEVER assert that a particular pg_catalog / information_schema relation \
appears in a list_objects listing, and never assert whether it is a "table" \
or a "view": pg_class/pg_index/pg_type are real tables while \
pg_settings/pg_stat_* are views, listings are filtered by the object_type \
you pass, and the distinction is never what a task is about. Verify such \
relations by SELECTing from them instead.
  - When the verified step read with a WHERE/ORDER BY/LIMIT, re-query with \
the SAME clauses before asserting counts or membership; NEVER assert against \
an unfiltered query when the step was filtered.
  - The database is SHARED and moves on after the trace: other work may add \
schemas/tables/rows between execution and verification. For catalog-level \
listings (schemas, tables, extensions) assert that expected items are \
PRESENT (subset/membership) — NEVER exact set equality or exact counts \
against the whole catalog. Exact row equality is fine INSIDE objects this \
task itself created.
  - You verify the END STATE only: every re-query runs AFTER the whole plan \
finished. NEVER assert a BEFORE-change condition live (the duplicate count \
before a DELETE, a value before an UPDATE) — those moments are gone; read \
them from the trace's own step outputs (executed_steps[*].result_data) and \
compare THOSE, then verify the final state live.
  - Extension objects (e.g. the pg_stat_statements view) install into the \
extension's schema — typically public, NOT pg_catalog. Verify an extension \
via "SELECT count(*) FROM pg_extension WHERE extname = '...'", never by \
looking for its view inside pg_catalog.
  - Never use bare next(...) or [0] on a possibly-empty result — use \
next(..., None) / guards, so one miss FAILS its check instead of crashing.
  - pg_rows returns None on ERROR and [] for zero rows — treat them \
differently (None -> the check fails with 'query failed').
  - In YOUR verification SELECTs, cast date/timestamp/numeric/interval \
columns to ::text (e.g. `sold_on::text AS sold_on`, `amount::text AS \
amount`): raw temporal/decimal values arrive as undecodable Python reprs and \
make the whole row read fail (pg_rows -> None). Compare against the string \
forms ('2024-01-15', '12.50'). Once you cast a column ::text, EVERY expected \
value for it must be a string too ('1', not 1) — never mix; rely on the \
query's ORDER BY for ordering, and NEVER compare ::text values with < / > \
(as text '9.99' sorts after '94.49') — convert with float()/int() first if \
you truly must compare magnitudes.
  - An unconstrained `numeric` column PRESERVES each literal's own scale, so \
a row seeded with 230.0 reads back '230.0' while one later set to 220 reads \
'220' — numerically equal, textually different. For numeric/decimal columns \
compare with float() (or round the column in SQL, e.g. \
round(voltage_max, 1)::text); never assert raw ::text equality on them.
  - pg_stat_statements and pg_stat_* counters are LIVE and move constantly — \
the verifier's own queries add to them. NEVER assert that a statement count, \
a total/mean time, a top-N ranking, or "the slowest query" still matches \
what the trace recorded, and never assert those numbers are stable or \
unchanged. Assert only what is structurally true: the tool returned rows, \
rows carry the expected keys, values are non-negative, or a specific known \
query TEXT appears somewhere in the result.
  - check() takes EXACTLY (category, name, passed, detail) — never other \
keyword arguments.
  - The session is READ-ONLY (restricted mode): only SELECT/SHOW/EXPLAIN can \
run. Effects of committed writes are immediately visible — no waiting needed. \
Use PLAIN `EXPLAIN <query>` only: `EXPLAIN (ANALYZE ...)` actually executes \
the query, so the read-only driver REJECTS it and your check silently reads \
None. Never put ANALYZE/BUFFERS/WAL options in a verification EXPLAIN.
  - A DOMAIN-typed column reports the BASE type: information_schema.columns \
gives data_type='integer' with the domain in `domain_name`, and pg_type's \
basetype reads as the internal alias ('int4', not 'integer'). Check \
`domain_name`, or verify the domain's CHECK clause / stored values instead \
of the column's data_type.
  - An extension's objects (the pg_stat_statements VIEW in particular) are \
created in the extension's own schema — normally `public`, NOT `pg_catalog`. \
To prove an extension is installed use \
pg_rows(pg, "SELECT count(*) AS c FROM pg_extension WHERE extname='...'"), \
and to inspect its view just SELECT from it; searching pg_catalog for it \
always fails.
  - One check(...) per assertion.
  - NEVER write an `import` statement. Everything you need is already in \
scope (the helpers, `check`, TRACE/PLAN, `time`); importing anything else — \
the server package, psycopg, pandas — raises ModuleNotFoundError and costs \
you the whole check.
  - This script may later be run again to score a DIFFERENT agent's \
trajectory over the SAME task (different step ids, step count and order). \
Locate a step by its TOOL (and, if needed, its arguments) — e.g. \
`next((s for s in executed_steps if s["tool"] == "analyze_db_health"), \
None)` — NEVER by a hardcoded step id ("s10") or list position \
(`executed_steps[7]`): both break the instant the trajectory differs even \
slightly, silently or with a crash.
  - When the task prose does NOT pin an exact object NAME (an index, \
constraint, etc. the agent was free to name itself), assert on its \
DEFINITION discovered live (columns it covers, its USING method) — never on \
a name the PLAN happened to invent. A differently-but-correctly-named \
object must not fail the check.
  - Never write a check whose assertion is true no matter what the trace or \
database actually contain (e.g. "the tool call did not raise"). Every \
check must be CAPABLE of catching a genuine defect, or it is not testing \
anything.
  - If you ORDER BY a column you also cast to ::text under an alias, order \
by the UNDERLYING typed expression, not the text alias — text ordering \
sorts '1','10','100','2',... which silently scrambles which row is \
"first"/"Nth".
  - NEVER call json.loads on a step's result_data or any string read from \
the trace. Values whose repr is not a pure literal (dates, Decimals) come \
back as a Python repr, not JSON — json.loads on them raises or silently \
misparses. Read the value directly (it is already a Python object from the \
trace), or re-query it live and cast ::text yourself.
  - A step's result_data is NOT guaranteed to be a list of dicts — a value \
containing a date/timestamp/Decimal decodes to a raw STRING instead (see \
the mcp_wrapper repr note). Check `isinstance(x, list)` (or `dict`) before \
iterating or indexing `executed_steps[i]["result_data"]`; iterating a \
string silently walks it character by character instead of raising.
  - Never hardcode a schema/table/object NAME copied from the plan, the \
trace, or an earlier (possibly failed) attempt into a live re-query. If the \
name might vary or the authoring run itself might have gotten it wrong, \
discover it live instead — e.g. filter pg_schemas(pg) by the task's own \
bench-prefix substring, or use pg_object_names — rather than trusting a \
literal string that could be stale or simply incorrect.
  - Don't assert a specific payload SHAPE you have not confirmed from the \
`executed_steps` you were given (e.g. "the tool returns a dict with a \
`preview` key"). Read what result_data actually contains and assert on \
that.
"""


_REPAIR_NOTE = """

REPAIR MODE. A previous version of this function (given as
`previous_dynamic_body`) already ran against the live database; execution of
the task itself SUCCEEDED, but the checks listed in `failed_checks` FAILED
with the details shown. For EACH failed check decide which of these it is:

  (a) the CHECK is wrong — a bug (exception, wrong catalog column, a
      forbidden pattern from the rules above) or a brittle comparison
      (bare == on values, re-derived formulas, exact text on normalized
      output). REWRITE it correctly, using vals_equal/rows_equal and the
      helpers. This is the common case.
  (b) the DATABASE genuinely does not satisfy what the task required. KEEP
      the check — it MUST keep failing; you may only sharpen its detail
      message.

Return the FULL corrected function body (all checks, not only the failed
ones — unchanged passing checks stay as they are). NEVER delete a check or
loosen it merely to make the report pass: a repair that hides a real
mismatch is worse than a false failure.
"""


def _isolate_exceptions(body: str) -> str:
    """Wrap each top-level statement of a (already compiling) dynamic body in
    its own try/except, so one crashing statement — a bad key access, an
    unexpected result shape — can no longer silently abort every check
    written after it. Measured across campaigns: a single such exception
    has cost 1-10 checks that never ran, shrinking `total` instead of
    failing loudly. Best-effort: any problem in this rewrite falls back to
    the ORIGINAL body unchanged — isolation must never make a working body
    worse, only contain a broken one."""
    try:
        probe = "def dynamic_evaluators(pg):\n" + textwrap.indent(body, "    ")
        tree = ast.parse(probe, mode="exec")
        fn = tree.body[0]
        wrapped = []
        for i, stmt in enumerate(fn.body):
            src = ast.unparse(stmt)
            guarded = ast.parse(
                "try:\n" + textwrap.indent(src, "    ")
                + f"\nexcept Exception as __iso_e{i}:\n"
                f'    check("dynamic", "isolated_exception_{i}", False, '
                f"repr(__iso_e{i}))\n"
            ).body[0]
            wrapped.append(guarded)
        fn.body = wrapped or fn.body
        rebuilt = ast.unparse(ast.fix_missing_locations(tree))
        inner = textwrap.dedent(rebuilt.split("\n", 1)[1])
        compile("def dynamic_evaluators(pg):\n" + textwrap.indent(inner, "    "),
                "<isolated>", "exec")
        return inner
    except Exception:
        return body


@dataclass
class VerificationReport:
    task: str
    total: int
    passed: int
    failed: int
    results: list[dict[str, Any]]
    script_path: str
    exit_code: int
    raw_stdout: str = ""
    raw_stderr: str = ""

    @property
    def ok(self) -> bool:
        return self.exit_code == 0 and self.total > 0 and self.failed == 0


class VerifierAgent:
    def __init__(self, settings: Settings, llm: LLMClient | None = None,
                 tool_names: list[str] | None = None):
        self.settings = settings
        self.llm = llm
        self.tool_names = tool_names or []

    # ------------------------------------------------------------------ public
    def build_script(self, plan: Plan, trace: ExecutionTrace,
                     dynamic_body: str | None = None) -> str:
        """Assemble verify.py and write it to work_dir. Returns its path.

        Assembled by concatenation (not one big str.format) so the helper code
        keeps normal braces; only the header has three sentinel substitutions.
        ``dynamic_body`` overrides LLM generation (used by the repair round).
        """
        self.settings.ensure_work_dir()
        if dynamic_body is None:
            dynamic_body = self._dynamic_body(plan, trace)
        self._last_body = dynamic_body
        tools_used = sorted({s.tool for s in plan.steps})
        header = (
            _HEADER
            .replace("__REPO_ROOT__", repr(str(self.settings.repo_root)))
            .replace("__SERVER_CMD__", repr([str(a) for a in self.settings.server_cmd] or None))
            .replace("__TOOLS_USED__", json.dumps(tools_used))
        )
        script = (
            header
            + _HELPERS
            + _FORMAT_STATIC
            + "\ndef dynamic_evaluators(pg):\n"
            + textwrap.indent(dynamic_body, "    ")
            + "\n"
            + _MAIN
        )
        path = self.settings.work_dir / "verify.py"
        path.write_text(script, encoding="utf-8")
        return str(path)

    def run_script(self, script_path: str) -> VerificationReport:
        """Execute verify.py in a subprocess and parse its JSON report."""
        uri = self.settings.database.uri
        env = _subprocess_env(uri)
        proc = subprocess.run(
            [sys.executable, script_path],
            cwd=str(self.settings.repo_root),
            capture_output=True,
            text=True,
            env=env,
            timeout=600,
        )
        report_obj: dict[str, Any] = {}
        # The script prints exactly one (pretty-printed) JSON report object.
        if proc.stdout.strip():
            try:
                report_obj = extract_json(proc.stdout)
            except ValueError:
                report_obj = {}
            if not isinstance(report_obj, dict):
                report_obj = {}
        return VerificationReport(
            task=report_obj.get("task", ""),
            total=report_obj.get("total", 0),
            passed=report_obj.get("passed", 0),
            failed=report_obj.get("failed", 0),
            results=report_obj.get("results", []),
            script_path=script_path,
            exit_code=proc.returncode,
            raw_stdout=proc.stdout,
            raw_stderr=proc.stderr,
        )

    def verify(self, plan: Plan, trace: ExecutionTrace) -> VerificationReport:
        path = self.build_script(plan, trace)
        report = self.run_script(path)
        repair_meta: dict[str, Any] | None = None

        # --- self-repair round -------------------------------------------
        # Measured across this project's runs, ~1-2% of LLM-AUTHORED checks
        # are buggy (brittle ==, wrong catalog column, an exception), which
        # compounds into spurious task failures on long trajectories. When
        # execution succeeded and the ONLY failures are LLM-authored dynamic
        # checks, give the model one look at its own failing checks: fix
        # checks that are wrong about the database; KEEP checks that are
        # right about a genuine mismatch. Deterministic layers (format,
        # static, sql_write) are never touched and re-run identically, so a
        # real failure cannot be repaired away. Both attempts are archived.
        if (not report.ok and report.total > 0 and self.llm is not None
                and trace.success and self._only_llm_dynamic_failures(report)):
            wd = self.settings.work_dir
            try:
                (wd / "verify.attempt1.py").write_text(
                    (wd / "verify.py").read_text(encoding="utf-8"),
                    encoding="utf-8")
            except OSError:
                pass
            first = report
            body2 = self._repair_body(plan, trace, first)
            if body2:
                path = self.build_script(plan, trace, dynamic_body=body2)
                report = self.run_script(path)
                repair_meta = {
                    "repaired": True,
                    "attempt1": {
                        "passed": first.passed, "total": first.total,
                        "failed_checks": [
                            {"name": r.get("name"),
                             "detail": str(r.get("detail", ""))[:200]}
                            for r in first.results if not r.get("passed")],
                    },
                }

        (self.settings.work_dir / "verification.json").write_text(
            json.dumps(
                {
                    "ok": report.ok,
                    "total": report.total,
                    "passed": report.passed,
                    "failed": report.failed,
                    "results": report.results,
                    "exit_code": report.exit_code,
                    **({"repair": repair_meta} if repair_meta else {}),
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        return report

    # ------------------------------------------------------- repair internals
    # sql_write_evaluators reports under category "dynamic" but is
    # deterministic code with structured names — never repair-eligible.
    _DET_DYNAMIC_RE = re.compile(
        r"^s\d+:(?:[a-z ]+_(?:exists|absent)|rows_present):|^sql_write_exception$")

    def _only_llm_dynamic_failures(self, report: VerificationReport) -> bool:
        """True when every failed check is LLM-authored (category dynamic and
        not one of the deterministic sql_write names)."""
        fails = [r for r in report.results if not r.get("passed")]
        return bool(fails) and all(
            r.get("category") == "dynamic"
            and not self._DET_DYNAMIC_RE.match(str(r.get("name", "")))
            for r in fails)

    def _repair_body(self, plan: Plan, trace: ExecutionTrace,
                     first: VerificationReport) -> str | None:
        """One corrected dynamic body, or None when the LLM reply is unusable."""
        failed = [r for r in first.results if not r.get("passed")]
        ctx = {
            "task": plan.task,
            "executed_steps": [
                {"id": s.id, "tool": s.tool,
                 "arguments_resolved": s.arguments_resolved,
                 "result_data": _truncate(s.result_data)}
                for s in trace.steps
            ],
            "previous_dynamic_body": getattr(self, "_last_body", ""),
            "failed_checks": [
                {"name": r.get("name"), "detail": str(r.get("detail", ""))[:300]}
                for r in failed],
        }
        user = json.dumps(ctx, default=str, indent=2)
        try:
            code = self.llm.chat(_DYNAMIC_SYSTEM + _REPAIR_NOTE, user,
                                 json_mode=False)
        except Exception:
            return None
        try:
            (self.settings.work_dir / "dynamic_raw.repair.txt").write_text(
                code, encoding="utf-8")
        except OSError:
            pass
        body = self._sanitize_body(code)
        # a repair that itself failed to compile is worthless — keep attempt 1
        return None if "LLM produced invalid python" in body else body

    # ------------------------------------------------------------------ internal
    def _dynamic_body(self, plan: Plan, trace: ExecutionTrace) -> str:
        if self.llm is None:
            return ('check("dynamic", "live_requery", True, '
                    '"skipped: no LLM configured for dynamic generation")')
        # Ground the LLM on the Python impl + unit test of the tools used,
        # preferring the prebuilt tool_sources KB (whole definition/test
        # functions) over the legacy first-mention grep, within a fixed
        # character budget split across the tools.
        tools_used = sorted({s.tool for s in plan.steps})
        budget = max(2400, 36000 // max(1, len(tools_used)))
        sources = [
            load_for_verifier(self.settings.repo_root, t, budget=budget)
            for t in tools_used
        ]
        ctx = {
            "task": plan.task,
            "available_tools": self.tool_names,
            "plan_steps": [
                {"id": s.id, "tool": s.tool, "arguments": s.arguments,
                 "post_action_properties": s.post_action_properties}
                for s in plan.steps
            ],
            "executed_steps": [
                {"id": s.id, "tool": s.tool, "arguments_resolved": s.arguments_resolved,
                 "result_data": _truncate(s.result_data)}
                for s in trace.steps
            ],
            "tool_sources": sources,
        }
        user = json.dumps(ctx, default=str, indent=2)
        code = self.llm.chat(_DYNAMIC_SYSTEM, user, json_mode=False)
        # Keep the raw reply for diagnosis: when the sanitizer has to stub a
        # syntactically-broken body, this file is the only way to see why.
        try:
            (self.settings.work_dir / "dynamic_raw.txt").write_text(
                code, encoding="utf-8")
        except OSError:
            pass
        return self._sanitize_body(code)

    @staticmethod
    def _sanitize_body(code: str) -> str:
        """Strip fences/`def` line; compile-check. Fall back to a safe stub."""
        code = code.strip()
        if "</think>" in code:
            code = code.rpartition("</think>")[2].strip()
        # Extract the first fenced block wherever it sits: models sometimes
        # prefix prose or a markdown heading BEFORE the fence ("# Verification
        # body\n```python..."), which startswith-only stripping missed — the
        # fence line then reached compile() and stubbed the whole layer.
        if "```" in code:
            parts = code.split("```")
            if len(parts) > 1 and parts[1].strip():
                code = parts[1]
                if code.lstrip().lower().startswith("python"):
                    code = code.lstrip()[6:]
        lines = code.strip("\n").splitlines()
        # drop a leading "def dynamic_evaluators(...):" if the model included it
        if lines and lines[0].lstrip().startswith("def dynamic_evaluators"):
            lines = lines[1:]
            lines = [textwrap.dedent("\n".join(lines))]
        body = "\n".join(lines).strip("\n") or "pass"
        # compile-check inside the target signature
        probe = "def dynamic_evaluators(pg):\n" + textwrap.indent(body, "    ")
        try:
            compile(probe, "<dynamic>", "exec")
        except SyntaxError as e:
            # Reasoning-tuned models drop typographic punctuation (em-dashes,
            # curly quotes) into code comments, which Python rejects as
            # "invalid character". The body was uncompilable as-is, so an
            # ASCII-fold retry can only gain: worst case a folded string
            # literal makes one runtime check fail instead of stubbing the
            # whole dynamic layer.
            if "invalid character" in str(e):
                folded = body.translate(str.maketrans({
                    "—": "-", "–": "-", "“": '"', "”": '"',
                    "‘": "'", "’": "'", "×": "*", "…": "..."}))
                probe2 = ("def dynamic_evaluators(pg):\n"
                          + textwrap.indent(folded, "    "))
                try:
                    compile(probe2, "<dynamic>", "exec")
                    return _isolate_exceptions(folded)
                except SyntaxError:
                    pass
            # repr() the WHOLE detail rather than hand-quoting it: an error
            # message containing a quote character used to make this stub
            # itself invalid Python, crashing verify.py into a 0/0 report.
            detail = "LLM produced invalid python: " + str(e)[:120]
            return f'check("dynamic", "live_requery", False, {detail!r})'
        return _isolate_exceptions(body)


def _truncate(data: Any, limit: int = 2000) -> Any:
    s = json.dumps(data, default=str)
    if len(s) <= limit:
        return data
    return {"_truncated": True, "preview": s[:limit]}


def _subprocess_env(database_uri: str) -> dict[str, str]:
    import os
    env = os.environ.copy()
    if database_uri:
        env["DATABASE_URI"] = database_uri
    return env


# ---------------------------------------------------------------------------
# The generated verify.py is assembled from these pieces. The deterministic
# Format/Static evaluators and the live-query helpers are fixed; only the
# dynamic body is LLM-authored, and it must use the helpers (not raw pg.call),
# which removes the recurring class of tool-signature/result-shape bugs.
# Three __SENTINEL__ tokens in _HEADER are replaced (not str.format) so the rest
# can use normal braces.
# ---------------------------------------------------------------------------
_HEADER = '''\
#!/usr/bin/env python3
"""Auto-generated execution-based verifier. Do not edit by hand."""
import json, os, re, sys, time
from pathlib import Path

REPO_ROOT = Path(__REPO_ROOT__)
SERVER_CMD = __SERVER_CMD__
TOOLS_USED = __TOOLS_USED__
sys.path.insert(0, str(REPO_ROOT))

HERE = Path(__file__).resolve().parent
TRACE = json.loads((HERE / "trace.json").read_text(encoding="utf-8"))
PLAN = json.loads((HERE / "plan.json").read_text(encoding="utf-8"))

# A dict that ALSO allows attribute access, so an LLM-generated dynamic check
# that writes step.result_data (instead of step["result_data"]) doesn't abort the
# whole dynamic section with AttributeError. Item access is unchanged; this only
# adds tolerance (same spirit as the shape-tolerant helpers below).
class _Step(dict):
    def __getattr__(self, k):
        try:
            return self[k]
        except KeyError:
            raise AttributeError(k)

# Aliases matching the names used in the dynamic-generation context, so the LLM
# can reference them directly without a NameError.
executed_steps = [_Step(s) for s in TRACE.get("steps", [])]
plan_steps = [_Step(s) for s in PLAN.get("steps", [])]
task = PLAN.get("task", "")

RESULTS = []
def check(category, name, passed, detail=""):
    RESULTS.append({"category": category, "name": name,
                    "passed": bool(passed), "detail": str(detail)[:400]})

def _step_result(step_id):
    for s in TRACE.get("steps", []):
        if s.get("id") == step_id:
            return _Step(s)
    return None
'''

# Correct, defensive live-query helpers. The dynamic body MUST use these.
_HELPERS = '''
def _decoded(res):
    """A ToolResult's structured payload; None when it is an error string."""
    d = res.data
    if isinstance(d, str) and d.lstrip().startswith("Error:"):
        return None
    return d

def pg_rows(pg, sql):
    """Run one read-only statement; rows as list[dict]. None on error, [] for
    zero rows ('No results' from the server means no rows came back)."""
    try:
        d = _decoded(pg.call("execute_sql", {"sql": sql}))
    except Exception:
        return None
    if d is None:
        return None
    if isinstance(d, str):
        return [] if "no results" in d.lower() else None
    if isinstance(d, dict):
        return [d]
    return [r for r in d if isinstance(r, dict)] if isinstance(d, list) else None

def pg_scalar(pg, sql):
    rows = pg_rows(pg, sql)
    if not rows:
        return None
    row = rows[0]
    for v in row.values():
        return v
    return None

def pg_schemas(pg):
    try:
        d = _decoded(pg.call("list_schemas", {}))
    except Exception:
        return []
    out = []
    for s in (d if isinstance(d, list) else []):
        if isinstance(s, dict) and s.get("schema_name"):
            out.append(str(s["schema_name"]).lower())
    return out

def pg_objects(pg, schema, object_type="table"):
    try:
        d = _decoded(pg.call("list_objects", {"schema_name": schema,
                                              "object_type": object_type}))
    except Exception:
        return []
    return [o for o in d if isinstance(o, dict)] if isinstance(d, list) else []

def pg_object_names(pg, schema, object_type="table"):
    return [str(o.get("name", "")).lower() for o in pg_objects(pg, schema, object_type)]

def _q(s):
    return str(s).replace("'", "''")

def pg_table_exists(pg, schema, table):
    n = pg_scalar(pg, "SELECT count(*) AS c FROM information_schema.tables "
                      "WHERE table_schema = '" + _q(str(schema).lower()) + "' "
                      "AND table_name = '" + _q(str(table).lower()) + "'")
    return bool(n)

def pg_columns(pg, schema, table):
    try:
        d = _decoded(pg.call("get_object_details", {"schema_name": schema,
                                                    "object_name": table,
                                                    "object_type": "table"}))
    except Exception:
        return []
    cols = d.get("columns") if isinstance(d, dict) else None
    return [c for c in cols if isinstance(c, dict)] if isinstance(cols, list) else []

def pg_constraints(pg, schema, table):
    try:
        d = _decoded(pg.call("get_object_details", {"schema_name": schema,
                                                    "object_name": table,
                                                    "object_type": "table"}))
    except Exception:
        return []
    cons = d.get("constraints") if isinstance(d, dict) else None
    return [c for c in cons if isinstance(c, dict)] if isinstance(cons, list) else []

def pg_indexes(pg, schema, table):
    try:
        d = _decoded(pg.call("get_object_details", {"schema_name": schema,
                                                    "object_name": table,
                                                    "object_type": "table"}))
    except Exception:
        return []
    idx = d.get("indexes") if isinstance(d, dict) else None
    return [i for i in idx if isinstance(i, dict)] if isinstance(idx, list) else []

def pg_matviews(pg, schema):
    """Materialized-view names in a schema (lowercased). They exist ONLY in
    pg_matviews — never in information_schema, so list_objects/
    get_object_details cannot see them."""
    rows = pg_rows(pg, "SELECT matviewname AS name FROM pg_matviews "
                       "WHERE schemaname = '" + _q(str(schema).lower()) + "'")
    return [str(r.get("name", "")).lower() for r in (rows or [])]

def pg_check_clauses(pg, schema, table):
    rows = pg_rows(pg,
        "SELECT tc.constraint_name AS name, cc.check_clause AS clause "
        "FROM information_schema.table_constraints tc "
        "JOIN information_schema.check_constraints cc "
        "ON tc.constraint_schema = cc.constraint_schema "
        "AND tc.constraint_name = cc.constraint_name "
        "WHERE tc.constraint_type = 'CHECK' "
        "AND tc.table_schema = '" + _q(str(schema).lower()) + "' "
        "AND tc.table_name = '" + _q(str(table).lower()) + "'")
    return rows or []

def pg_count(pg, qualified_table, where=None):
    sql = "SELECT count(*) AS c FROM " + str(qualified_table)
    if where:
        sql += " WHERE " + str(where)
    v = pg_scalar(pg, sql)
    try:
        return int(v)
    except (TypeError, ValueError):
        return None

def _normv(v):
    """One value, normalized for tolerant comparison: numerics (including
    numeric STRINGS — ::text casts and unconstrained-numeric scale make
    '100', 100, '230.0' and 230 all legitimate spellings of the same value)
    compare as floats; everything else as a stripped, lowercased string."""
    if isinstance(v, bool):
        return v
    if isinstance(v, (int, float)):
        return round(float(v), 6)
    s = str(v).strip()
    try:
        return round(float(s), 6)
    except ValueError:
        return s.lower()

def vals_equal(a, b):
    """Tolerant scalar equality — ALWAYS use this instead of == for values
    read back from the database."""
    return _normv(a) == _normv(b)

def rows_equal(rows, expected, ordered=True):
    """Tolerant row comparison. `rows` is a pg_rows result (list[dict]);
    `expected` is a list of dicts (same column aliases) or tuples (values in
    SELECT order). Numeric strings and ints compare equal; identifier case is
    ignored. Returns False (never raises) on None/shape mismatch."""
    if rows is None or expected is None:
        return False
    def _norm_row(r):
        vals = r.values() if isinstance(r, dict) else r
        return tuple(_normv(x) for x in vals)
    try:
        a = [_norm_row(r) for r in rows]
        b = [_norm_row(r) for r in expected]
    except (TypeError, AttributeError):
        return False
    return a == b if ordered else sorted(a) == sorted(b)

def pg_column_domain(pg, schema, table, column):
    """The DOMAIN a column is typed with (lowercased), or None. This is the
    ONLY reliable place a domain shows up for a column — data_type reports
    the base type."""
    v = pg_scalar(pg, "SELECT domain_name FROM information_schema.columns "
                      "WHERE table_schema = '" + _q(str(schema).lower()) + "' "
                      "AND table_name = '" + _q(str(table).lower()) + "' "
                      "AND column_name = '" + _q(str(column).lower()) + "'")
    return str(v).lower() if v else None

def poll(predicate, timeout=30, interval=5):
    """Call predicate() -> (ok, value) until ok is truthy or timeout. Returns (ok, value)."""
    end = time.time() + timeout
    ok, val = False, None
    while True:
        try:
            ok, val = predicate()
        except Exception:
            ok, val = False, None
        if ok or time.time() >= end:
            return ok, val
        time.sleep(interval)
'''

_FORMAT_STATIC = '''
# ---------------- (1) Format Evaluators ----------------
# Only what is reliably knowable from the trace: did the step run and succeed,
# is there a result. Output-content correctness is the Dynamic layer's job.
def format_evaluators():
    for pstep in PLAN.get("steps", []):
        sid = pstep.get("id")
        tr = _step_result(sid)
        if tr is None:
            check("format", f"{sid}:executed", False, "step missing from trace")
            continue
        ok = tr.get("status") == "success"
        check("format", f"{sid}:status", ok,
              "success" if ok else f"status={tr.get('status')} error={tr.get('error')}")
        if ok:
            data = tr.get("result_data")
            # A benign idempotent success ("already exists" / ledger skip)
            # legitimately carries no real payload — the effect pre-existed.
            idem = any(a.get("status") == "success_idempotent"
                       for a in tr.get("attempts") or [])
            present = idem or (data is not None and data != "")
            check("format", f"{sid}:result_present", present,
                  "idempotent (effect already present)" if idem
                  else f"type={type(data).__name__}")

# -------------- (1b) Deterministic live SQL-write checks --------------
# Every executed CREATE/DROP is re-checked live at the exact object it named,
# and every INSERT contributes a row-count floor for its table. No LLM
# judgment involved — this is the authoritative DDL/rowcount check (the
# dynamic section is told not to repeat bare existence checks and to verify
# CONTENT instead). Objects a later statement removed are asserted ABSENT.
_CREATE_RE = re.compile(
    r"^\\s*create\\s+(?:or\\s+replace\\s+)?(?:unique\\s+)?(?:temp(?:orary)?\\s+)?"
    r"(table|view|materialized\\s+view|schema|sequence|index|extension"
    r"|type|domain)\\s+"
    r"(?:concurrently\\s+)?(?:if\\s+not\\s+exists\\s+)?([\\w.\\"$]+)", re.IGNORECASE)
_DROP_RE = re.compile(
    r"^\\s*drop\\s+(table|view|materialized\\s+view|schema|sequence|index"
    r"|extension|type|domain)\\s+"
    r"(?:concurrently\\s+)?(?:if\\s+exists\\s+)?([\\w.\\"$]+)", re.IGNORECASE)
_INSERT_TBL_RE = re.compile(r"^\\s*insert\\s+into\\s+([\\w.\\"$]+)", re.IGNORECASE)
_VALUES_RE = re.compile(r"\\bvalues\\b", re.IGNORECASE)

def _split_statements(sql):
    """';'-separated statements, ignoring a ';' inside a quoted literal. An
    agent may legitimately batch several statements in one execute_sql call
    (the planner's one-per-step house style is not enforced on others);
    classifying only the FIRST silently ignored every statement after it."""
    out, buf, in_s, in_d = [], [], False, False
    for ch in sql:
        if ch == "'" and not in_d:
            in_s = not in_s
        elif ch == '"' and not in_s:
            in_d = not in_d
        if ch == ";" and not in_s and not in_d:
            out.append("".join(buf))
            buf = []
            continue
        buf.append(ch)
    if buf:
        out.append("".join(buf))
    return [s.strip() for s in out if s.strip()]

def _split_name(raw):
    name = str(raw).replace('"', "").lower().rstrip(";,(")
    if "." in name:
        sch, _, obj = name.partition(".")
        return sch, obj
    return "public", name

def _exists_sql(otype, sch, obj):
    if otype == "schema":
        return ("SELECT count(*) AS c FROM information_schema.schemata "
                "WHERE schema_name = '" + _q(obj) + "'")
    if otype == "table":
        return ("SELECT count(*) AS c FROM information_schema.tables "
                "WHERE table_schema = '" + _q(sch) + "' AND table_name = '" + _q(obj) + "'")
    if otype == "view":
        return ("SELECT count(*) AS c FROM information_schema.views "
                "WHERE table_schema = '" + _q(sch) + "' AND table_name = '" + _q(obj) + "'")
    if otype == "materialized view":
        return ("SELECT count(*) AS c FROM pg_matviews "
                "WHERE schemaname = '" + _q(sch) + "' AND matviewname = '" + _q(obj) + "'")
    if otype == "sequence":
        return ("SELECT count(*) AS c FROM information_schema.sequences "
                "WHERE sequence_schema = '" + _q(sch) + "' AND sequence_name = '" + _q(obj) + "'")
    if otype == "index":
        return "SELECT count(*) AS c FROM pg_indexes WHERE indexname = '" + _q(obj) + "'"
    if otype in ("type", "domain"):
        # enum types and domains both live in pg_type, keyed by namespace
        return ("SELECT count(*) AS c FROM pg_type t "
                "JOIN pg_namespace n ON n.oid = t.typnamespace "
                "WHERE n.nspname = '" + _q(sch) + "' AND t.typname = '" + _q(obj) + "'")
    if otype == "extension":
        return "SELECT count(*) AS c FROM pg_extension WHERE extname = '" + _q(obj) + "'"
    return None

def sql_write_evaluators(pg):
    if pg is None:
        return
    last_op = {}      # (otype, schema, name) -> (sid, "exists"|"absent")
    insert_floor = {} # (schema, table) -> [sid, n_statements]
    for tr in TRACE.get("steps", []):
        if tr.get("status") != "success" or tr.get("tool") != "execute_sql":
            continue
        sql = (tr.get("arguments_resolved") or {}).get("sql") or ""
        sid = tr.get("id")
        # A step may batch multiple ';'-separated statements even when the
        # planner's own house style is one-per-step (other agents batch
        # freely) — classify EVERY statement, not just the first, so
        # last-op-wins semantics see the whole batch in order.
        for stmt in _split_statements(sql):
            m = _CREATE_RE.match(stmt)
            if m:
                otype = re.sub(r"\\s+", " ", m.group(1).lower())
                sch, obj = _split_name(m.group(2))
                if obj and obj != "on":  # unnamed "CREATE INDEX ON t" -> no name to check
                    last_op[(otype, sch, obj)] = (sid, "exists")
                continue
            m = _DROP_RE.match(stmt)
            if m:
                otype = re.sub(r"\\s+", " ", m.group(1).lower())
                sch, obj = _split_name(m.group(2))
                last_op[(otype, sch, obj)] = (sid, "absent")
                if otype in ("table", "materialized view"):
                    insert_floor.pop((sch, obj), None)
                if otype == "schema":
                    for key in [k for k in insert_floor if k[0] == obj]:
                        insert_floor.pop(key, None)
                continue
            m = _INSERT_TBL_RE.match(stmt)
            if m and _VALUES_RE.search(stmt):
                sch, obj = _split_name(m.group(1))
                ent = insert_floor.setdefault((sch, obj), [sid, 0])
                ent[1] += 1
                continue
            head = stmt.lstrip().split(None, 1)
            kind = head[0].lower() if head else ""
            if kind in ("truncate", "delete"):
                low = stmt.lower()
                for (sch, obj) in list(insert_floor):
                    if obj in low:
                        insert_floor.pop((sch, obj), None)
    for (otype, sch, obj), (sid, expect) in last_op.items():
        q = _exists_sql(otype, sch, obj)
        if q is None:
            continue
        n = pg_scalar(pg, q)
        if n is None:
            check("dynamic", f"{sid}:{otype}_{expect}:{sch}.{obj}", False,
                  "live existence query failed")
            continue
        ok = (int(n) > 0) if expect == "exists" else (int(n) == 0)
        check("dynamic", f"{sid}:{otype}_{expect}:{sch}.{obj}", ok,
              f"live count={n}, expected {'>=1' if expect == 'exists' else '0'}")
    for (sch, obj), (sid, floor) in insert_floor.items():
        if ("table", sch, obj) in last_op and last_op[("table", sch, obj)][1] == "absent":
            continue
        n = pg_count(pg, f"{sch}.{obj}")
        ok = n is not None and n >= floor
        check("dynamic", f"{sid}:rows_present:{sch}.{obj}", ok,
              f"live rowcount={n}, expected >= {floor} (one per executed INSERT)")

# ---------------- (2) Static Evaluators ----------------
# Value checks on the INPUTS actually sent: SQL non-empty and single-statement;
# key string args non-empty.
def static_evaluators():
    for pstep in PLAN.get("steps", []):
        sid = pstep.get("id")
        tr = _step_result(sid)
        if tr is None or tr.get("status") != "success":
            continue
        args = tr.get("arguments_resolved") or {}
        for k, v in args.items():
            if isinstance(v, str) and k in ("sql", "schema_name", "object_name", "health_type"):
                check("static", f"{sid}:argnonempty[{k}]", v.strip() != "",
                      f"{k} must be non-empty")
            if isinstance(v, int) and not isinstance(v, bool) and k in ("limit", "max_index_size_mb"):
                check("static", f"{sid}:argpos[{k}]", v > 0, f"{k}={v} must be positive")
        # NOTE: no single-statement check here. "One statement per step" is
        # the PLANNER's house style (warned at plan time), not a property of
        # task correctness — and this verifier also scores other agents'
        # trajectories (e.g. the ReAct baseline), which legitimately batch
        # statements. Keeping it here penalized style, not substance.

def _strip_quoted(sql):
    out, in_s, in_d = [], False, False
    for ch in sql:
        if ch == "'" and not in_d:
            in_s = not in_s
            continue
        if ch == '"' and not in_s:
            in_d = not in_d
            continue
        if not in_s and not in_d:
            out.append(ch)
    return "".join(out)

# ---------------- (3) Dynamic Evaluators (LLM-generated, uses helpers) ----------------
'''

_MAIN = '''
def _open_pg():
    uri = os.environ.get("DATABASE_URI") or os.environ.get("AGENTICMCPE_DATABASE_URI")
    if not uri:
        return None
    try:
        from pkg.mcp_wrapper import MCPClient
        pg = MCPClient(database_uri=uri,
                       server_cmd=SERVER_CMD,
                       access_mode="restricted")
        pg.start()
        return pg
    except Exception as e:
        check("dynamic", "client_init", False, f"could not start MCP client: {e}")
        return None

def main():
    format_evaluators()
    static_evaluators()
    pg = _open_pg()
    try:
        sql_write_evaluators(pg)
    except Exception as e:
        check("dynamic", "sql_write_exception", False, repr(e))
    try:
        dynamic_evaluators(pg)
    except Exception as e:  # a bad dynamic check must not crash verification
        check("dynamic", "dynamic_exception", False, repr(e))
    finally:
        if pg is not None:
            try:
                pg.close()
            except Exception:
                pass
    passed = sum(1 for r in RESULTS if r["passed"])
    report = {
        "task": PLAN.get("task", ""),
        "total": len(RESULTS),
        "passed": passed,
        "failed": len(RESULTS) - passed,
        "results": RESULTS,
    }
    print(json.dumps(report, indent=2))
    sys.exit(0 if RESULTS and passed == len(RESULTS) else 1)

if __name__ == "__main__":
    main()
'''


__all__ = ["VerifierAgent", "VerificationReport"]
