"""Verifier agent: generate + run an execution-based verification script.

The verifier proves the task was carried out correctly. It assembles ONE python
script (``verify.py``) combining three evaluator families, then executes it:

  (1) Format Evaluators  — strict structure checks on each step's outcome.
      Deterministic, trace-only.
  (2) Static Evaluators  — value checks on the INPUTS actually sent (URLs are
      http(s) and non-empty, interaction targets non-empty, waits positive).
      Deterministic.
  (3) Dynamic Evaluators — checks generated by the LLM, grounded on the tool
      catalog (description + inputSchema) and the executed trace. Primary
      evidence is the RECORDED session: browser state is ephemeral, so the
      snapshots captured in the trace ARE the state at execution time. Live
      re-query is limited to re-navigating public URLs from the trace in a
      FRESH observation-only session (playwright-mcp has no read-only mode;
      the session is restricted client-side to observation tools).

Plus a deterministic live layer between (2) and (3): every executed
``browser_navigate`` with a literal http(s) URL is re-navigated live and must
resolve (redirects allowed) — the browser analog of the GitHub port's
byte-exact file re-fetch.

This hybrid (deterministic core + LLM-only-for-dynamic) is the key reliability
optimization over fully LLM-generated verification scripts.
"""

from __future__ import annotations

import json
import subprocess
import sys
import textwrap
from dataclasses import dataclass
from typing import Any

from .catalog import tool_grounding
from .config import LLMClient, Settings, extract_json
from .executor import ExecutionTrace
from .planner import Plan

_DYNAMIC_SYSTEM = """\
You write the BODY of one Python function that VERIFIES a browser task was done \
correctly.

You are given (as JSON): the task, available_tools, the plan steps with their \
post_action_properties, the executed steps with arguments_resolved and \
result_data, and the catalog entry (description + inputSchema) of the tools \
used.

Write ONLY Python statements (no `def` line, no imports, no markdown) forming \
the body of:  def dynamic_evaluators(pw):

THE EVIDENCE IS THE RECORDED TRACE. Browser state is ephemeral — the \
execution session is gone — and the snapshots recorded in executed_steps ARE \
the page state at execution time. Write TRACE-ONLY checks. Do NOT write \
live-browser checks: a separate deterministic layer already re-navigates \
every executed URL live, and live pages legitimately differ from the recorded \
run (volatile content, rate limits), so a live content check turns a correct \
execution into a false failure.

USE ONLY THESE pre-defined helpers:
  - step_text(step_id) -> str            # an executed step's recorded result text ("" if none)
  - all_text() -> str                    # every successful step's recorded text, joined
  - final_url() / final_title() -> str|None   # page URL/title after the LAST successful step
  - norm(s) -> str                       # whitespace-collapsed, casefolded
  - has(hay, needle) -> bool             # norm(needle) in norm(hay)
Also in scope: check(category, name, passed, detail) — ALWAYS category="dynamic", \
and EXACTLY those arguments: one name string, ONE boolean, one detail string \
(fold every extra value into the detail string; a fifth argument is a \
TypeError that kills the whole dynamic section); \
the TRACE and PLAN dicts; the `time` and `re` modules. TRACE and PLAN are DICTS — \
to iterate steps use the list aliases `executed_steps` (= TRACE["steps"]) and \
`plan_steps` (= PLAN["steps"]); NEVER iterate TRACE or PLAN directly. The `pw` \
argument and the pw_goto/pw_snapshot/pw_find/pw_wait/pw_url/poll helpers \
belong to the deterministic layer — IGNORE them completely; referencing them \
fails validation.

Rules:
  - Derive URLs, search terms and expected texts from the TASK and from \
executed_steps[*].arguments_resolved. Never hardcode placeholders.
  - Verify the OBSERVABLE OUTCOMES the task asked for, NOT implementation \
details: the recorded snapshots contain the expected page (title, headings, \
result entries); the final page URL matches where the task should end up; the \
information the task asked to extract (a price, a name, a count) actually \
appears in a recorded snapshot.
  - VOLATILE values (prices, availability, live scores) change between runs: \
assert their PRESENCE/FORMAT in the recorded trace (e.g. a currency amount \
appears in the snapshot after the search), never a specific live value.
  - Your context may show a result_data as truncated ("_truncated" preview) — \
the trace the checks run against is FULL: still test with \
has(step_text(...), ...), and NEVER conclude something is absent merely \
because your context preview was cut off.
  - The recorded text of browser_wait_for, browser_close and most ACTIONS is \
often EMPTY — that is normal, never assert it non-empty, and never write any \
check ABOUT the wait/close steps themselves (the format layer already covers \
their status). Page content lives in browser_snapshot / browser_find results \
only.
  - Pages may render a LOCALIZED UI (titles and labels in Chinese or another \
language, e.g. Google Maps titles like "…至… - Google 地图"). Match \
language-neutral evidence — entity names, numbers, URLs — as they appear in \
the recorded trace; never require English UI words ("Directions") or an \
English page title.
  - A task may legitimately be completed across SEVERAL sites; never require \
the FINAL page to be on a particular site — verify that each required piece \
of information appears SOMEWHERE in the recorded trace.
  - PORTABLE CHECKS: your script may be re-run against a DIFFERENT valid \
execution of the same task (different step count and ids). Prefer \
all_text() / final_url() / final_title() over step_text("sN"); reference a \
specific step id only when the task truly hinges on that exact step's \
output. A check should test the TASK's outcome, not this plan's shape.
  - Text matching: always compare with has()/norm() — snapshots wrap and \
indent text arbitrarily.
  - Never use bare next(...) or [0] on a possibly-empty lookup — use \
next(..., None) / guards, so one miss FAILS its check instead of crashing.
  - Write times, dates, scores and ids as STRINGS ("07:30", "1,234") — bare \
literals like 07:30 or 1,234 are Python syntax errors.
  - Define every variable before you use it; your code runs exactly as sent, \
and one NameError aborts every later check.
  - One check(...) per assertion.
"""


@dataclass
class VerificationReport:
    task: str
    total: int
    passed: int
    failed: int
    results: list[dict[str, Any]]
    script_path: str
    exit_code: int
    raw_stdout: str = ""
    raw_stderr: str = ""

    @property
    def ok(self) -> bool:
        return self.exit_code == 0 and self.total > 0 and self.failed == 0


class VerifierAgent:
    def __init__(self, settings: Settings, llm: LLMClient | None = None,
                 tool_names: list[str] | None = None):
        self.settings = settings
        self.llm = llm
        self.tool_names = tool_names or []

    # ------------------------------------------------------------------ public
    def build_script(self, plan: Plan, trace: ExecutionTrace) -> str:
        """Assemble verify.py and write it to work_dir. Returns its path.

        Assembled by concatenation (not one big str.format) so the helper code
        keeps normal braces; only the header has sentinel substitutions.
        """
        self.settings.ensure_work_dir()
        dynamic_body = self._dynamic_body(plan, trace)
        tools_used = sorted({s.tool for s in plan.steps})
        header = (
            _HEADER
            .replace("__REPO_ROOT__", repr(str(self.settings.repo_root)))
            .replace("__SERVER_CMD__", json.dumps(self.settings.server_command))
            .replace("__TOOLS_USED__", json.dumps(tools_used))
        )
        script = (
            header
            + _HELPERS
            + _FORMAT_STATIC
            + "\ndef dynamic_evaluators(pw):\n"
            + textwrap.indent(dynamic_body, "    ")
            + "\n"
            + _MAIN
        )
        path = self.settings.work_dir / "verify.py"
        path.write_text(script, encoding="utf-8")
        return str(path)

    def run_script(self, script_path: str) -> VerificationReport:
        """Execute verify.py in a subprocess and parse its JSON report.

        A verify.py that crashes or times out yields NO report — that must
        surface as a diagnosable FAILING verification, never as a silent 0/0
        (batch evidence: 7/35 runs reported 0 checks with the cause visible
        only in an unstored stderr)."""
        import os
        try:
            proc = subprocess.run(
                [sys.executable, script_path],
                cwd=str(self.settings.repo_root),
                capture_output=True,
                text=True,
                env=os.environ.copy(),
                timeout=600,
            )
            returncode, stdout, stderr = proc.returncode, proc.stdout, proc.stderr
        except subprocess.TimeoutExpired as e:
            returncode = -1
            stdout = (e.stdout or b"").decode("utf-8", "replace") \
                if isinstance(e.stdout, bytes) else (e.stdout or "")
            stderr = ((e.stderr or b"").decode("utf-8", "replace")
                      if isinstance(e.stderr, bytes) else (e.stderr or ""))
            stderr += "\nverify.py timed out after 600s"
        report_obj: dict[str, Any] = {}
        # The script prints exactly one (pretty-printed) JSON report object.
        if stdout.strip():
            try:
                report_obj = extract_json(stdout)
            except ValueError:
                report_obj = {}
            if not isinstance(report_obj, dict):
                report_obj = {}
        if not report_obj:
            tail = (stderr or stdout or "").strip()[-800:]
            report_obj = {
                "task": "",
                "total": 1,
                "passed": 0,
                "failed": 1,
                "results": [{
                    "category": "format",
                    "name": "verify_script_ran",
                    "passed": False,
                    "detail": (f"verify.py produced no JSON report "
                               f"(exit={returncode}). Output tail: "
                               f"{tail or '(empty)'}")[:400],
                }],
            }
        return VerificationReport(
            task=report_obj.get("task", ""),
            total=report_obj.get("total", 0),
            passed=report_obj.get("passed", 0),
            failed=report_obj.get("failed", 0),
            results=report_obj.get("results", []),
            script_path=script_path,
            exit_code=returncode,
            raw_stdout=stdout,
            raw_stderr=stderr,
        )

    def verify(self, plan: Plan, trace: ExecutionTrace) -> VerificationReport:
        path = self.build_script(plan, trace)
        report = self.run_script(path)
        (self.settings.work_dir / "verification.json").write_text(
            json.dumps(
                {
                    "ok": report.ok,
                    "total": report.total,
                    "passed": report.passed,
                    "failed": report.failed,
                    "results": report.results,
                    "exit_code": report.exit_code,
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        return report

    # ------------------------------------------------------------------ internal
    def _dynamic_body(self, plan: Plan, trace: ExecutionTrace) -> str:
        if self.llm is None:
            return ('check("dynamic", "live_requery", True, '
                    '"skipped: no LLM configured for dynamic generation")')
        # Ground the LLM on each used tool's catalog entry (description +
        # inputSchema) — playwright-mcp's implementation lives in the bundled
        # playwright-core package, so the catalog is the grounding source.
        tools_used = sorted({s.tool for s in plan.steps})
        budget = max(2400, 36000 // max(1, len(tools_used)))
        sources = [
            tool_grounding(self.settings, t, max_chars=budget)
            for t in tools_used
        ]
        ctx = {
            "task": plan.task,
            "available_tools": self.tool_names,
            "plan_steps": [
                {"id": s.id, "tool": s.tool, "arguments": s.arguments,
                 "post_action_properties": s.post_action_properties}
                for s in plan.steps
            ],
            "executed_steps": [
                {"id": s.id, "tool": s.tool, "arguments_resolved": s.arguments_resolved,
                 # Snapshots/finds carry the page evidence the checks must
                 # read — give them a much larger preview (a tight cut made
                 # the model conclude content was absent and hardcode a fail).
                 "result_data": _truncate(
                     s.result_data,
                     8000 if s.tool in ("browser_snapshot", "browser_find")
                     else 2600)}
                for s in trace.steps
            ],
            "tool_catalog_entries": sources,
        }
        user = json.dumps(ctx, default=str, indent=2)
        return generate_dynamic_body(self.llm, user)


def _clean_code(code: str) -> str:
    """Strip think-blocks / markdown fences / a stray `def` line from an LLM
    reply, leaving the bare statement body."""
    code = code.strip()
    if "</think>" in code:
        code = code.rpartition("</think>")[2].strip()
    if code.startswith("```"):
        parts = code.split("```")
        code = parts[1] if len(parts) > 1 else code
        if code.lstrip().lower().startswith("python"):
            code = code.lstrip()[6:]
    lines = code.strip("\n").splitlines()
    # drop a leading "def dynamic_evaluators(...):" if the model included it
    if lines and lines[0].lstrip().startswith("def dynamic_evaluators"):
        lines = lines[1:]
        lines = [textwrap.dedent("\n".join(lines))]
    return "\n".join(lines).strip("\n") or "pass"


def _compile_error(body: str) -> str | None:
    """Compile-check ``body`` inside the target signature. None when it
    compiles; the SyntaxError text otherwise."""
    probe = "def dynamic_evaluators(pw):\n" + textwrap.indent(body, "    ")
    try:
        compile(probe, "<dynamic>", "exec")
    except SyntaxError as e:
        return str(e)
    return None


# Names the generated body may legitimately reference: the helper kit +
# aliases injected by the script header, common stdlib modules in scope, and
# a generous builtin set. Anything else that is read but never assigned is a
# guaranteed NameError at run time.
_KNOWN_NAMES = frozenset({
    "check", "step_text", "all_text", "final_url", "final_title", "norm",
    "has", "pw_goto", "pw_snapshot", "pw_find", "pw_wait", "pw_url", "poll",
    "pw", "TRACE", "PLAN", "executed_steps", "plan_steps", "task",
    "time", "re", "json",
})
_KNOWN_BUILTINS = frozenset({
    "len", "str", "int", "float", "bool", "any", "all", "next", "sorted",
    "enumerate", "range", "isinstance", "sum", "min", "max", "abs", "round",
    "list", "dict", "set", "tuple", "zip", "filter", "map", "reversed",
    "print", "repr", "getattr", "hasattr", "type", "format", "divmod",
    "Exception", "ValueError", "TypeError", "KeyError", "IndexError",
    "AttributeError", "StopIteration", "ZeroDivisionError", "RuntimeError",
})


def _lint_error(body: str) -> str | None:
    """Static checks for the runtime failures compile() cannot see — both
    observed killing entire dynamic sections: check() called with extra
    positional values (TypeError) and references to names never defined
    (NameError). Returns a message for the retry prompt, or None."""
    import ast
    try:
        tree = ast.parse("def dynamic_evaluators(pw):\n"
                         + textwrap.indent(body, "    "))
    except SyntaxError as e:  # _compile_error runs first; belt and braces
        return str(e)
    live = frozenset({"pw", "pw_goto", "pw_snapshot", "pw_find", "pw_wait",
                      "pw_url", "poll"})
    problems: list[str] = []
    stored: set[str] = set()   # names the body itself binds (may shadow)
    args: set[str] = set()     # function args (the wrapper's own `pw`)
    for node in ast.walk(tree):
        if isinstance(node, ast.Name) and isinstance(node.ctx,
                                                     (ast.Store, ast.Del)):
            stored.add(node.id)
        elif isinstance(node, (ast.Import, ast.ImportFrom)):
            for a in node.names:
                stored.add((a.asname or a.name).split(".")[0])
        elif isinstance(node, ast.arg):
            args.add(node.arg)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            stored.add(node.name)
        elif isinstance(node, ast.ExceptHandler) and node.name:
            stored.add(node.name)
    known = _KNOWN_NAMES | _KNOWN_BUILTINS | stored | args
    for node in ast.walk(tree):
        if (isinstance(node, ast.Call) and isinstance(node.func, ast.Name)
                and node.func.id == "check"):
            n_args = len(node.args) + len(node.keywords)
            if not 3 <= n_args <= 4:
                problems.append(
                    f"check() takes 3-4 arguments (category, name, passed, "
                    f"detail) but a call passes {n_args} — fold extra values "
                    f"into the detail string")
        if (isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load)
                and node.id in live and node.id not in stored):
            problems.append(
                f"'{node.id}' is a live-browser facility and is disabled — "
                f"write TRACE-ONLY checks (the deterministic layer already "
                f"re-verifies every URL live)")
        elif (isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load)
                and node.id not in known):
            problems.append(f"name '{node.id}' is never defined "
                            f"(would raise NameError)")
    if problems:
        return "; ".join(sorted(set(problems))[:5])
    return None


def generate_dynamic_body(llm: Any, user: str, *, attempts: int = 3) -> str:
    """Ask the LLM for the dynamic-evaluator body; on a compile failure, re-ask
    with the compiler's error attached (up to ``attempts`` total calls).

    Batch evidence made this the single largest verification failure: 9/35
    runs produced a non-compiling body on the first try, and the fallback stub
    (a hard-coded failing check) was the ONLY failing check in most of them.
    Compilers give precise feedback, so one corrective round-trip usually
    repairs the body; only after exhausting retries do we fall back to the
    stub, now annotated with the final error.
    """
    err: str | None = None
    for _ in range(max(1, attempts)):
        prompt = user
        if err is not None:
            prompt = (
                user
                + "\n\nYOUR PREVIOUS REPLY FAILED TO COMPILE OR LINT.\n"
                + f"Problem: {err}\n"
                + "Common causes: an apostrophe inside a single-quoted string; "
                  "a time/score/id written as a bare literal (write \"07:30\", "
                  "\"1,234\" as STRINGS); extra positional values passed to "
                  "check(); referencing a name you never defined; using pw or "
                  "the live pw_* helpers (disabled — trace-only checks); "
                  "stray markdown or backticks. Resend the ENTIRE corrected "
                  "body — plain Python statements only."
            )
        body = _clean_code(llm.chat(_DYNAMIC_SYSTEM, prompt, json_mode=False))
        err = _compile_error(body) or _lint_error(body)
        if err is None:
            return body
    # json.dumps guarantees the embedded message is a valid Python string
    # literal — repr() switched quote style when the error text itself
    # contained quotes, producing a fallback stub that crashed the whole
    # generated script with a SyntaxError of its own.
    detail = json.dumps(
        f"LLM produced invalid python after {max(1, attempts)} attempt(s): "
        + str(err)[:120])
    return f'check("dynamic", "live_requery", False, {detail})'


def _truncate(data: Any, limit: int = 2600) -> Any:
    s = json.dumps(data, default=str)
    if len(s) <= limit:
        return data
    return {"_truncated": True, "preview": s[:limit]}


# ---------------------------------------------------------------------------
# The generated verify.py is assembled from these pieces. The deterministic
# Format/Static evaluators and the live-query helpers are fixed; only the
# dynamic body is LLM-authored, and it must use the helpers (not raw pw.call),
# which removes the recurring class of tool-signature/result-shape bugs.
# The __SENTINEL__ tokens in _HEADER are replaced (not str.format) so the rest
# can use normal braces.
# ---------------------------------------------------------------------------
_HEADER = '''\
#!/usr/bin/env python3
"""Auto-generated execution-based verifier. Do not edit by hand."""
import json, os, re, sys, time
from pathlib import Path

REPO_ROOT = Path(__REPO_ROOT__)
SERVER_CMD = __SERVER_CMD__
TOOLS_USED = __TOOLS_USED__
sys.path.insert(0, str(REPO_ROOT))

HERE = Path(__file__).resolve().parent
TRACE = json.loads((HERE / "trace.json").read_text(encoding="utf-8"))
PLAN = json.loads((HERE / "plan.json").read_text(encoding="utf-8"))

# A dict that ALSO allows attribute access, so an LLM-generated dynamic check
# that writes step.result_data (instead of step["result_data"]) doesn't abort the
# whole dynamic section with AttributeError. Item access is unchanged; this only
# adds tolerance (same spirit as the shape-tolerant helpers below).
class _Step(dict):
    def __getattr__(self, k):
        try:
            return self[k]
        except KeyError:
            raise AttributeError(k)

# Aliases matching the names used in the dynamic-generation context, so the LLM
# can reference them directly without a NameError.
executed_steps = [_Step(s) for s in TRACE.get("steps", [])]
plan_steps = [_Step(s) for s in PLAN.get("steps", [])]
task = PLAN.get("task", "")

RESULTS = []
def check(category, name, passed, detail=""):
    RESULTS.append({"category": category, "name": name,
                    "passed": bool(passed), "detail": str(detail)[:400]})

def _step_result(step_id):
    for s in TRACE.get("steps", []):
        if s.get("id") == step_id:
            return _Step(s)
    return None
'''

# Correct, defensive helpers. The dynamic body MUST use these. Trace helpers
# need no browser; pw_* helpers drive the fresh observation-only session.
_HELPERS = '''
def _result_text(s):
    d = s.get("result_data")
    if isinstance(d, dict):
        return d.get("text") or ""
    return d if isinstance(d, str) else ""

def step_text(step_id):
    s = _step_result(step_id)
    return _result_text(s) if s else ""

def all_text():
    return "\\n".join(_result_text(s) for s in TRACE.get("steps", [])
                      if s.get("status") == "success")

def _last_page_field(key):
    for s in reversed(TRACE.get("steps", [])):
        if s.get("status") != "success":
            continue
        d = s.get("result_data")
        if isinstance(d, dict) and d.get(key):
            return d[key]
    return None

def final_url():
    return _last_page_field("url")

def final_title():
    return _last_page_field("title")

def norm(s):
    return re.sub(r"\\s+", " ", str(s or "")).strip().casefold()

def has(hay, needle):
    return norm(needle) in norm(hay)

def pw_snapshot(pw):
    try:
        d = pw.call("browser_snapshot", {}).data
    except Exception:
        return None
    return d if isinstance(d, str) else None

def pw_goto(pw, url):
    try:
        pw.call("browser_navigate", {"url": url})
    except Exception:
        return None
    return pw_snapshot(pw)

def pw_find(pw, text):
    try:
        d = pw.call("browser_find", {"text": text}).data
    except Exception:
        return None
    return d if isinstance(d, str) else None

def pw_wait(pw, text=None, seconds=None):
    args = {}
    if text:
        args["text"] = text
    if seconds:
        args["time"] = seconds
    if not args:
        return False
    try:
        pw.call("browser_wait_for", args)
        return True
    except Exception:
        return False

def pw_url(pw):
    snap = pw_snapshot(pw)
    if not snap:
        return None
    m = re.search(r"^- Page URL: (.+)$", snap, re.MULTILINE)
    return m.group(1).strip() if m else None

def poll(predicate, timeout=60, interval=5):
    """Call predicate() -> (ok, value) until ok is truthy or timeout. Returns (ok, value)."""
    end = time.time() + timeout
    ok, val = False, None
    while True:
        try:
            ok, val = predicate()
        except Exception:
            ok, val = False, None
        if ok or time.time() >= end:
            return ok, val
        time.sleep(interval)
'''

_FORMAT_STATIC = '''
# ---------------- (1) Format Evaluators ----------------
# Only what is reliably knowable from the trace: did the step run and succeed,
# is there a result. Output-content correctness is the Dynamic layer's job.
def format_evaluators():
    for pstep in PLAN.get("steps", []):
        sid = pstep.get("id")
        tr = _step_result(sid)
        if tr is None:
            check("format", f"{sid}:executed", False, "step missing from trace")
            continue
        ok = tr.get("status") == "success"
        check("format", f"{sid}:status", ok,
              "success" if ok else f"status={tr.get('status')} error={str(tr.get('error'))[:160]}")
        if ok:
            data = tr.get("result_data")
            # A benign idempotent success (browser already closed) legitimately
            # carries a stub payload.
            idem = any(a.get("status") == "success_idempotent"
                       for a in tr.get("attempts") or [])
            present = idem or (data is not None and data != "")
            check("format", f"{sid}:result_present", present,
                  "idempotent (state already held)" if idem
                  else f"type={type(data).__name__}")

# -------------- (1b) Deterministic live navigation checks --------------
# Every executed browser_navigate with a literal http(s) URL is re-navigated
# live and must load (redirects allowed). This is the browser analog of the
# GitHub port's deterministic re-fetch of authored file writes. No LLM
# judgment involved.
def nav_evaluators(pw):
    if pw is None:
        return
    seen = set()
    for tr in TRACE.get("steps", []):
        if tr.get("status") != "success" or tr.get("tool") != "browser_navigate":
            continue
        url = (tr.get("arguments_resolved") or {}).get("url")
        if not isinstance(url, str) or not url.startswith(("http://", "https://")):
            continue
        if url in seen:
            continue
        seen.add(url)
        snap = pw_goto(pw, url)
        if snap is None:
            # One retry after a pause: a transient third-party flake at
            # verify time must not fail a correct execution.
            time.sleep(3)
            snap = pw_goto(pw, url)
        ok = snap is not None
        live = pw_url(pw) if ok else None
        check("dynamic", f"{tr.get('id')}:nav_reachable:{url[:80]}", ok,
              f"resolved to {live}" if ok else "live navigation failed")

# ---------------- (2) Static Evaluators ----------------
# Value checks on the INPUTS actually sent.
def static_evaluators():
    for pstep in PLAN.get("steps", []):
        sid = pstep.get("id")
        tr = _step_result(sid)
        if tr is None or tr.get("status") != "success":
            continue
        args = tr.get("arguments_resolved") or {}
        tool = tr.get("tool")
        if tool == "browser_navigate":
            url = args.get("url")
            check("static", f"{sid}:url_scheme",
                  isinstance(url, str) and url.startswith(("http://", "https://")),
                  f"url={str(url)[:120]}")
        if "target" in args:
            v = args.get("target")
            check("static", f"{sid}:target_nonempty",
                  isinstance(v, str) and v.strip() != "", f"target={str(v)[:80]}")
        if tool == "browser_wait_for" and isinstance(args.get("time"), (int, float)):
            check("static", f"{sid}:wait_positive", args["time"] > 0,
                  f"time={args['time']}")

# ---------------- (3) Dynamic Evaluators (LLM-generated, uses helpers) ----------------
'''

_MAIN = '''
# playwright-mcp has no --read-only mode; the verification session is
# restricted CLIENT-side to observation + navigation tools (re-establishing
# state on public pages is the browser analog of a read-only re-query).
_RO_TOOLS = [
    "browser_navigate", "browser_navigate_back", "browser_snapshot",
    "browser_find", "browser_wait_for", "browser_console_messages",
    "browser_network_requests", "browser_network_request",
    "browser_take_screenshot", "browser_close",
]

def _open_pw():
    try:
        from pkg.mcp_wrapper import MCPClient
        pw = MCPClient(command=SERVER_CMD, headless=True, isolated=True,
                       allow_tools=_RO_TOOLS)
        pw.start()
        return pw
    except Exception as e:
        check("dynamic", "client_init", False, f"could not start MCP client: {e}")
        return None

def main():
    format_evaluators()
    static_evaluators()
    pw = _open_pw()
    try:
        nav_evaluators(pw)
    except Exception as e:
        check("dynamic", "nav_exception", False, repr(e))
    try:
        dynamic_evaluators(pw)
    except Exception as e:  # a bad dynamic check must not crash verification
        check("dynamic", "dynamic_exception", False, repr(e))
    finally:
        if pw is not None:
            try:
                pw.close()
            except Exception:
                pass
    passed = sum(1 for r in RESULTS if r["passed"])
    report = {
        "task": PLAN.get("task", ""),
        "total": len(RESULTS),
        "passed": passed,
        "failed": len(RESULTS) - passed,
        "results": RESULTS,
    }
    print(json.dumps(report, indent=2))
    sys.exit(0 if RESULTS and passed == len(RESULTS) else 1)

if __name__ == "__main__":
    main()
'''


__all__ = ["VerifierAgent", "VerificationReport", "generate_dynamic_body"]
